# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wasted' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'TextFieldEffects'
  pod "MBCircularProgressBar"
  pod 'FSCalendar'

  target 'WastedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WastedUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
